name: Run MyPy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pyflakes flake8 lxml
    - name: Lint with mypy
      run: mypy --cobertura-xml-report .
             -p IPython.terminal
             -p IPython.core.magics
    - name: Lint with pyflakes
      run: |
        flake8  IPython/core/magics/script.py
        flake8  IPython/core/magics/packaging.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        name: MyPy
